export const EMERGENCY_SCENARIOS = [
  {
    id_safe: 'Aman - Tabungan Darurat Menyelamatkanmu', en_safe: 'Secure - Emergency Fund Saves You',
    id_danger: 'Pinalti - Terpaksa Utang Pinjol', en_danger: 'Penalty - Forced High-Interest Debt',
    id_title: 'Sakit Mendadak! 🏥', en_title: 'Medical Emergency! 🏥',
    id_desc_safe: 'Anggota keluarga tiba-tiba sakit! Untungnya, tabungan daruratmu menutupi biaya kamar rumah sakit tanpa berutang sama sekali.', en_desc_safe: 'A family member fell ill! Fortunately, your emergency fund covers the bills completely without taking debt.',
    id_desc_danger: 'Anggota keluarga mendadak sakit parah! Karena kamu tidak ada tabungan darurat, kamu terpaksa meminjam uang secara online dengan bunga sangat tinggi.', en_desc_danger: 'A family member fell ill! Without savings, you were forced to take a toxic high-interest online loan.'
  },
  {
    id_safe: 'Aman - Klaim Asuransi Cair', en_safe: 'Secure - Insurance Claimed',
    id_danger: 'Pinalti - Gaji Habis Untuk Perbaikan', en_danger: 'Penalty - Salary Drained for Repairs',
    id_title: 'Atap Rumah Bocor! 🌧️', en_title: 'Leaking Home Roof! 🌧️',
    id_desc_safe: 'Hujan badai membuat atap rumah bocor. Dengan dana darurat, kamu langsung memanggil tukang untuk memperbaiki atap.', en_desc_safe: 'A heavy storm broke your home roof. With emergency funds, you fixed it smoothly.',
    id_desc_danger: 'Hujan badai membuat atap rumah bocor parah! Karena absennya tabungan dana darurat, uang jatah makan bulan ini habis untuk perbaikan atap.', en_desc_danger: 'A heavy storm broke your home roof! With no savings, your grocery budget was drained entirely.'
  },
  {
    id_safe: 'Aman - Servis Langsung Cepat', en_safe: 'Secure - Quick Instant Service',
    id_danger: 'Pinalti - Transportasi Pekerjaan Terhambat', en_danger: 'Penalty - Transport Disrupted',
    id_title: 'Motor Mogok di Jalan! 🏍️', en_title: 'Motorcycle Broke Down! 🏍️',
    id_desc_safe: 'Motormu tiba-tiba mogok di jalan raya. Untungnya kamu menggunakan porsi tabungan darurat untuk biaya biaya bengkel mendadak ini.', en_desc_safe: 'Your motorcycle broke down. You confidently used emergency savings for sudden repairs.',
    id_desc_danger: 'Motormu mogok di jalan raya! Kamu sama sekali tidak punya simpanan, terpaksa berutang ke teman dan terlambat kerja beberapa hari.', en_desc_danger: 'Motorcycle broke down! Absolute zero savings forced you to borrow from peers and miss work.'
  }
];

export const LEVEL_ORDERS: Record<number, { text: string, text_en: string, type: string }[]> = {
  0: [
    { text: "Beli Beras Bulan Ini", text_en: "This Month Buy Sack of Rice", type: "KEBUTUHAN" },
    { text: "Beli Unit Reksadana Mingguan Biasa", text_en: "Standard Weekly Routine Buy Mutual Funds Units", type: "TABUNGAN" },
    { text: "Modus SMS Selamat Pemenang Untuk Keluarga", text_en: "For the Extended Family Fake Winner Congratulations SMS", type: "TRAP" },
    { text: "Tabungan Koin Recehan Super Cepat dan Praktis", text_en: "Super Fast and Practical Keep Coin Savings", type: "TABUNGAN" },
    { text: "Beli Jam Tangan Branded Mewah Bulan Depan", text_en: "Next Month Scheduled Buy Branded Luxury Watch", type: "KEINGINAN" },
    { text: "Sisihkan Gaji Bulanan Rutin Mendadak Mendesak", text_en: "Suddenly Very Urgent Set Aside Routine Monthly Salary", type: "TABUNGAN" },
    { text: "Bayar Listrik Bulan Lalu Tertunda", text_en: "Delayed from Last Month Pay Electricity Bill", type: "KEBUTUHAN" },
    { text: "Beli Gas Dapur Habis Hari Ini Secara Tunai", text_en: "Today in Cash Buy Kitchen Gas Cylinder", type: "KEBUTUHAN" },
    { text: "Instal APK Kurir Ekspedisi Bodong Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Install Fake Courier Tracking APK", type: "TRAP" },
    { text: "Beli Air Minum Galon Edisi Premium Terbaru", text_en: "Latest Premium Edition Buy Drinking Water Gallon", type: "KEBUTUHAN" },
    { text: "Beli Akun Game Palsu Termurah", text_en: "Buy Cheapest Fake Gaming Account", type: "TRAP" },
    { text: "Transfer Uang Jebakan Pajak Mingguan Biasa", text_en: "Standard Weekly Routine Fake Tax Trap Money Transfer", type: "TRAP" },
    { text: "Beli Obat-obatan Apotek Untuk Keluarga", text_en: "For the Extended Family Buy Pharmacy Medicines", type: "KEBUTUHAN" },
    { text: "Sisihkan Modal Buka Usaha Super Cepat dan Praktis", text_en: "Super Fast and Practical Set Aside New Business Capital", type: "TABUNGAN" },
    { text: "Bayar Langganan Netflix", text_en: "Pay Netflix Monthly Subscription", type: "KEINGINAN" },
    { text: "Beli Emas Mini Investasi", text_en: "Buy Investment Mini Gold", type: "TABUNGAN" },
    { text: "Liburan Staycation Hotel Mewah Bulan Lalu Tertunda", text_en: "Delayed from Last Month Luxury Hotel Staycation Vacation", type: "KEINGINAN" },
    { text: "Bayar Langganan Premium Spotify Hari Ini Secara Tunai", text_en: "Today in Cash Pay Spotify Premium Subscription", type: "KEINGINAN" },
    { text: "Uang Ongkos Transportasi Bekerja", text_en: "Work Commute Transport Fare", type: "KEBUTUHAN" },
    { text: "Tabungan Hewan Qurban", text_en: "Save for Charity Slaughter", type: "TABUNGAN" },
    { text: "Beli Beras", text_en: "Buy Sack of Rice", type: "KEBUTUHAN" },
    { text: "Beli Sepatu Sneakers Modis", text_en: "Buy Stylish Sneakers Shoes", type: "KEINGINAN" },
    { text: "Beli SBN Surat Berharga Ritel", text_en: "Buy Retail Government Bonds", type: "TABUNGAN" },
    { text: "Beli Sayur", text_en: "Buy Vegetables", type: "KEBUTUHAN" },
    { text: "Skema Ponzi Menguntungkan Bulan Depan", text_en: "Next Month Scheduled Highly Profitable Ponzi Scheme", type: "TRAP" },
    { text: "Bayar Kontrakan Rumah Mendadak Mendesak", text_en: "Suddenly Very Urgent Pay House Lease", type: "KEBUTUHAN" },
    { text: "Bayar Listrik Bulan Lalu Tertunda", text_en: "Delayed from Last Month Pay Electricity Bill", type: "KEBUTUHAN" },
    { text: "Setor Dana Pensiun Tua Hari Ini Secara Tunai", text_en: "Today in Cash Deposit into Pension Fund", type: "TABUNGAN" },
    { text: "Belanja Sembako Mingguan Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Buy Basic Weekly Groceries", type: "KEBUTUHAN" },
    { text: "Sisihkan Dana Darurat", text_en: "Set Aside Emergency Fund", type: "TABUNGAN" },
    { text: "Beli Surat Obligasi Negara", text_en: "Buy Government Treasury Bonds", type: "TABUNGAN" },
    { text: "Jajan Minuman Teh Kekinian Mingguan Biasa", text_en: "Standard Weekly Routine Buy Trendy Sweet Tea", type: "KEINGINAN" },
    { text: "Beli Deposito Berjangka Bank Untuk Keluarga", text_en: "For the Extended Family Buy Bank Time Deposit", type: "TABUNGAN" },
    { text: "Beli Action Figure Jutaan Super Cepat dan Praktis", text_en: "Super Fast and Practical Buy Expensive Action Figure", type: "KEINGINAN" },
    { text: "Bayar Langganan Netflix Bulan Depan", text_en: "Next Month Scheduled Pay Netflix Monthly Subscription", type: "KEINGINAN" },
    { text: "Top Up Skin Game Eksklusif Mendadak Mendesak", text_en: "Suddenly Very Urgent Top Up Exclusive Game Skin", type: "KEINGINAN" },
    { text: "Bayar Premi Asuransi Kesehatan", text_en: "Pay Health Insurance Premium", type: "TABUNGAN" },
    { text: "Bayar Iuran Warga Desa Hari Ini Secara Tunai", text_en: "Today in Cash Pay Community Dues", type: "KEBUTUHAN" },
    { text: "Uang Ongkos Transportasi Bekerja Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Work Commute Transport Fare", type: "KEBUTUHAN" },
    { text: "Lowongan Kerja Palsu Meminta Uang Edisi Premium Terbaru", text_en: "Latest Premium Edition Fake Job Vacancy Asking Pre-Money", type: "TRAP" },
    { text: "Beli Beras Bulan Ini", text_en: "This Month Buy Sack of Rice", type: "KEBUTUHAN" },
    { text: "Beli Unit Reksadana", text_en: "Buy Mutual Funds Units", type: "TABUNGAN" },
    { text: "Beli SBN Surat Berharga Ritel", text_en: "Buy Retail Government Bonds", type: "TABUNGAN" },
    { text: "Tabungan Koin Recehan", text_en: "Keep Coin Savings", type: "TABUNGAN" },
    { text: "Beli Saham Unggulan Blue Chip", text_en: "Buy Blue Chip Corporation Stocks", type: "TABUNGAN" },
    { text: "Beli Kosmetik Brand Mahal Mendadak Mendesak", text_en: "Suddenly Very Urgent Buy Expensive Cosmetic Brands", type: "KEINGINAN" },
    { text: "Setor Rekening Bank Bulan Lalu Tertunda", text_en: "Delayed from Last Month Deposit into Bank Account", type: "TABUNGAN" },
    { text: "Beli Gas Dapur Habis Hari Ini Secara Tunai", text_en: "Today in Cash Buy Kitchen Gas Cylinder", type: "KEBUTUHAN" },
    { text: "Modal Koperasi Simpan Pinjam", text_en: "Deposit into Savings Cooperative", type: "TABUNGAN" },
    { text: "Makan Mewah di Luar Edisi Premium Terbaru", text_en: "Latest Premium Edition Fancy Eat Out Dinner", type: "KEINGINAN" },
    { text: "Beli Surat Obligasi Negara", text_en: "Buy Government Treasury Bonds", type: "TABUNGAN" },
    { text: "Transfer Uang Jebakan Pajak Mingguan Biasa", text_en: "Standard Weekly Routine Fake Tax Trap Money Transfer", type: "TRAP" },
    { text: "Beli Deposito Berjangka Bank Untuk Keluarga", text_en: "For the Extended Family Buy Bank Time Deposit", type: "TABUNGAN" },
    { text: "Beli Pasta Gigi", text_en: "Buy Toothpaste", type: "KEBUTUHAN" },
    { text: "Bayar Langganan Netflix", text_en: "Pay Netflix Monthly Subscription", type: "KEINGINAN" }
  ],
  1: [
    { text: "Sisihkan Modal Buka Usaha Bulan Ini", text_en: "This Month Set Aside New Business Capital", type: "TABUNGAN" },
    { text: "Bayar Langganan Netflix Mingguan Biasa", text_en: "Standard Weekly Routine Pay Netflix Monthly Subscription", type: "KEINGINAN" },
    { text: "Top Up Skin Game Eksklusif", text_en: "Top Up Exclusive Game Skin", type: "KEINGINAN" },
    { text: "Bayar Premi Asuransi Kesehatan Super Cepat dan Praktis", text_en: "Super Fast and Practical Pay Health Insurance Premium", type: "TABUNGAN" },
    { text: "Bayar Iuran Warga Desa Bulan Depan", text_en: "Next Month Scheduled Pay Community Dues", type: "KEBUTUHAN" },
    { text: "Uang Ongkos Transportasi Bekerja Mendadak Mendesak", text_en: "Suddenly Very Urgent Work Commute Transport Fare", type: "KEBUTUHAN" },
    { text: "Lowongan Kerja Palsu Meminta Uang Bulan Lalu Tertunda", text_en: "Delayed from Last Month Fake Job Vacancy Asking Pre-Money", type: "TRAP" },
    { text: "Beli Beras Hari Ini Secara Tunai", text_en: "Today in Cash Buy Sack of Rice", type: "KEBUTUHAN" },
    { text: "Klik Link WA Phishing Undangan", text_en: "Clicking WA Phishing Invite Link", type: "TRAP" },
    { text: "Beli Baju Fashion Diskonan Edisi Premium Terbaru", text_en: "Latest Premium Edition Buy Fashion Clothes on Discount", type: "KEINGINAN" },
    { text: "Main Game Dingdong Arcade", text_en: "Play Arcade Dingdong Games", type: "KEINGINAN" },
    { text: "Beli Susu Anak Formula", text_en: "Buy Baby Milk Formula", type: "KEBUTUHAN" },
    { text: "Sisihkan Gaji Bulanan Rutin", text_en: "Set Aside Routine Monthly Salary", type: "TABUNGAN" },
    { text: "Setor Rekening Bank Super Cepat dan Praktis", text_en: "Super Fast and Practical Deposit into Bank Account", type: "TABUNGAN" },
    { text: "Langganan Streaming VIP Bulan Depan", text_en: "Next Month Scheduled Pay VIP Streaming Subscription", type: "KEINGINAN" },
    { text: "Belanja Sembako Mingguan", text_en: "Buy Basic Weekly Groceries", type: "KEBUTUHAN" },
    { text: "Beli Air Minum Galon", text_en: "Buy Drinking Water Gallon", type: "KEBUTUHAN" },
    { text: "Beli Tiket Konser K-Pop", text_en: "Buy K-Pop Concert Ticket", type: "KEINGINAN" },
    { text: "Bayar Premi Asuransi Jiwa Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Pay Life Insurance Premium", type: "TABUNGAN" },
    { text: "Beli Deposito Berjangka Bank", text_en: "Buy Bank Time Deposit", type: "TABUNGAN" },
    { text: "Beli Pasta Gigi Bulan Ini", text_en: "This Month Buy Toothpaste", type: "KEBUTUHAN" },
    { text: "Beli Emas Batangan Murni Mingguan Biasa", text_en: "Standard Weekly Routine Buy Pure Gold Bar Solid", type: "TABUNGAN" },
    { text: "Top Up Skin Game Eksklusif Untuk Keluarga", text_en: "For the Extended Family Top Up Exclusive Game Skin", type: "KEINGINAN" },
    { text: "Bayar Premi Asuransi Kesehatan Super Cepat dan Praktis", text_en: "Super Fast and Practical Pay Health Insurance Premium", type: "TABUNGAN" },
    { text: "Cicil Beli Tanah Investasi Bulan Depan", text_en: "Next Month Scheduled Installment for Land Investment", type: "TABUNGAN" },
    { text: "Uang Ongkos Transportasi Bekerja Mendadak Mendesak", text_en: "Suddenly Very Urgent Work Commute Transport Fare", type: "KEBUTUHAN" },
    { text: "Beli Makanan Pokok", text_en: "Buy Staple Daily Foods", type: "KEBUTUHAN" },
    { text: "Isi Celengan Ayam Hari Ini Secara Tunai", text_en: "Today in Cash Fill Piggy Bank", type: "TABUNGAN" },
    { text: "Beli Unit Reksadana", text_en: "Buy Mutual Funds Units", type: "TABUNGAN" },
    { text: "Modus SMS Selamat Pemenang Edisi Premium Terbaru", text_en: "Latest Premium Edition Fake Winner Congratulations SMS", type: "TRAP" },
    { text: "Investasi Bodong Saham Palsu", text_en: "Fake Stock Market Investment", type: "TRAP" },
    { text: "Beli Jam Tangan Branded Mewah Mingguan Biasa", text_en: "Standard Weekly Routine Buy Branded Luxury Watch", type: "KEINGINAN" },
    { text: "Bayar Kontrakan Rumah Untuk Keluarga", text_en: "For the Extended Family Pay House Lease", type: "KEBUTUHAN" },
    { text: "Koleksi Stiker Lucu Super Cepat dan Praktis", text_en: "Super Fast and Practical Collect Cute Stickers", type: "KEINGINAN" },
    { text: "Beli Gas Dapur Habis Bulan Depan", text_en: "Next Month Scheduled Buy Kitchen Gas Cylinder", type: "KEBUTUHAN" },
    { text: "Beli Aksesoris Pakaian Mendadak Mendesak", text_en: "Suddenly Very Urgent Buy Clothing Accessories", type: "KEINGINAN" },
    { text: "Sisihkan Dana Darurat Bulan Lalu Tertunda", text_en: "Delayed from Last Month Set Aside Emergency Fund", type: "TABUNGAN" },
    { text: "Beli Surat Obligasi Negara Hari Ini Secara Tunai", text_en: "Today in Cash Buy Government Treasury Bonds", type: "TABUNGAN" },
    { text: "Beli Lauk Pauk Sayur Mayur Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Buy Vegetables & Meats", type: "KEBUTUHAN" },
    { text: "Beli Obat-obatan Apotek", text_en: "Buy Pharmacy Medicines", type: "KEBUTUHAN" },
    { text: "Investasi Scam Kripto Abal-Abal", text_en: "Fake Garbage Crypto Investment", type: "TRAP" },
    { text: "Beli Emas Batangan Murni Mingguan Biasa", text_en: "Standard Weekly Routine Buy Pure Gold Bar Solid", type: "TABUNGAN" },
    { text: "Beli Sabun Mandi Untuk Keluarga", text_en: "For the Extended Family Buy Bath Soap", type: "KEBUTUHAN" },
    { text: "Bayar Premi Asuransi Kesehatan Super Cepat dan Praktis", text_en: "Super Fast and Practical Pay Health Insurance Premium", type: "TABUNGAN" },
    { text: "Cicil Beli Tanah Investasi Bulan Depan", text_en: "Next Month Scheduled Installment for Land Investment", type: "TABUNGAN" },
    { text: "Nongkrong di Kafe Gaul Mendadak Mendesak", text_en: "Suddenly Very Urgent Hangout at Trendy Cafe", type: "KEINGINAN" },
    { text: "Beli Makanan Pokok", text_en: "Buy Staple Daily Foods", type: "KEBUTUHAN" },
    { text: "Isi Celengan Ayam", text_en: "Fill Piggy Bank", type: "TABUNGAN" },
    { text: "Beli Unit Reksadana Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Buy Mutual Funds Units", type: "TABUNGAN" },
    { text: "Beli Baju Fashion Diskonan Edisi Premium Terbaru", text_en: "Latest Premium Edition Buy Fashion Clothes on Discount", type: "KEINGINAN" },
    { text: "Tabungan Koin Recehan", text_en: "Keep Coin Savings", type: "TABUNGAN" },
    { text: "Beli Jam Tangan Branded Mewah", text_en: "Buy Branded Luxury Watch", type: "KEINGINAN" },
    { text: "Beli Kosmetik Brand Mahal Untuk Keluarga", text_en: "For the Extended Family Buy Expensive Cosmetic Brands", type: "KEINGINAN" },
    { text: "Koleksi Stiker Lucu", text_en: "Collect Cute Stickers", type: "KEINGINAN" },
    { text: "Modus Pesugihan Online Gaib Bulan Depan", text_en: "Next Month Scheduled Online Occult Ritual Scam", type: "TRAP" }
  ],
  2: [
    { text: "Arisan Online Fiktif Admin Kabur", text_en: "Online Fictitious Gatherings Scam", type: "TRAP" },
    { text: "Modus Pesugihan Online Gaib", text_en: "Online Occult Ritual Scam", type: "TRAP" },
    { text: "Modal Koperasi Simpan Pinjam", text_en: "Deposit into Savings Cooperative", type: "TABUNGAN" },
    { text: "Beli Air Minum Galon Super Cepat dan Praktis", text_en: "Super Fast and Practical Buy Drinking Water Gallon", type: "KEBUTUHAN" },
    { text: "Beli Tiket Konser K-Pop Bulan Depan", text_en: "Next Month Scheduled Buy K-Pop Concert Ticket", type: "KEINGINAN" },
    { text: "Bayar Premi Asuransi Jiwa Mendadak Mendesak", text_en: "Suddenly Very Urgent Pay Life Insurance Premium", type: "TABUNGAN" },
    { text: "Aplikasi Pinjol Bunga 50% Bulan Lalu Tertunda", text_en: "Delayed from Last Month Loan Sharks App 50% Interest", type: "TRAP" },
    { text: "Beli Pasta Gigi Hari Ini Secara Tunai", text_en: "Today in Cash Buy Toothpaste", type: "KEBUTUHAN" },
    { text: "E-Mail Penipuan Perusahaan Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Corporate Scam Phishing Email", type: "TRAP" },
    { text: "Beli Emas Mini Investasi", text_en: "Buy Investment Mini Gold", type: "TABUNGAN" },
    { text: "Bayar Premi Asuransi Kesehatan Bulan Ini", text_en: "This Month Pay Health Insurance Premium", type: "TABUNGAN" },
    { text: "Bayar Iuran Warga Desa Mingguan Biasa", text_en: "Standard Weekly Routine Pay Community Dues", type: "KEBUTUHAN" },
    { text: "Grup Telegram Bot Trading Scam Untuk Keluarga", text_en: "For the Extended Family Telegram Trading Bot Scam Group", type: "TRAP" },
    { text: "Lowongan Kerja Palsu Meminta Uang Super Cepat dan Praktis", text_en: "Super Fast and Practical Fake Job Vacancy Asking Pre-Money", type: "TRAP" },
    { text: "Jajan Minuman Boba", text_en: "Buy Sweet Boba Drink", type: "KEINGINAN" },
    { text: "Klik Link WA Phishing Undangan Mendadak Mendesak", text_en: "Suddenly Very Urgent Clicking WA Phishing Invite Link", type: "TRAP" },
    { text: "Beli Vitamin Harian Keluarga Bulan Lalu Tertunda", text_en: "Delayed from Last Month Buy Family Daily Vitamins", type: "KEBUTUHAN" },
    { text: "Investasi Bodong Saham Palsu Hari Ini Secara Tunai", text_en: "Today in Cash Fake Stock Market Investment", type: "TRAP" },
    { text: "Beli Jam Tangan Branded Mewah", text_en: "Buy Branded Luxury Watch", type: "KEINGINAN" },
    { text: "Beli Kosmetik Brand Mahal Edisi Premium Terbaru", text_en: "Latest Premium Edition Buy Expensive Cosmetic Brands", type: "KEINGINAN" },
    { text: "Bayar Listrik", text_en: "Pay Electricity Bill", type: "KEBUTUHAN" },
    { text: "Setor Dana Pensiun Tua", text_en: "Deposit into Pension Fund", type: "TABUNGAN" },
    { text: "Beli Aksesoris Pakaian Untuk Keluarga", text_en: "For the Extended Family Buy Clothing Accessories", type: "KEINGINAN" },
    { text: "Makan Mewah di Luar", text_en: "Fancy Eat Out Dinner", type: "KEINGINAN" },
    { text: "Beli Tiket Konser K-Pop Bulan Depan", text_en: "Next Month Scheduled Buy K-Pop Concert Ticket", type: "KEINGINAN" },
    { text: "Transfer Uang Jebakan Pajak Mendadak Mendesak", text_en: "Suddenly Very Urgent Fake Tax Trap Money Transfer", type: "TRAP" },
    { text: "Beli Obat-obatan Apotek Bulan Lalu Tertunda", text_en: "Delayed from Last Month Buy Pharmacy Medicines", type: "KEBUTUHAN" },
    { text: "Beli Action Figure Jutaan Hari Ini Secara Tunai", text_en: "Today in Cash Buy Expensive Action Figure", type: "KEINGINAN" },
    { text: "Beli Emas Batangan Murni Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Buy Pure Gold Bar Solid", type: "TABUNGAN" },
    { text: "Tawaran Cepat Kaya Instan Edisi Premium Terbaru", text_en: "Latest Premium Edition Instant Get Rich Quick Offer", type: "TRAP" },
    { text: "Bayar Premi Asuransi Kesehatan Bulan Ini", text_en: "This Month Pay Health Insurance Premium", type: "TABUNGAN" },
    { text: "Cicil Beli Tanah Investasi Mingguan Biasa", text_en: "Standard Weekly Routine Installment for Land Investment", type: "TABUNGAN" },
    { text: "Uang Ongkos Transportasi Bekerja Untuk Keluarga", text_en: "For the Extended Family Work Commute Transport Fare", type: "KEBUTUHAN" },
    { text: "Tabungan Hewan Qurban Super Cepat dan Praktis", text_en: "Super Fast and Practical Save for Charity Slaughter", type: "TABUNGAN" },
    { text: "Isi Celengan Ayam Bulan Depan", text_en: "Next Month Scheduled Fill Piggy Bank", type: "TABUNGAN" },
    { text: "Bayar Sewa Kosan", text_en: "Pay Room Rent", type: "KEBUTUHAN" },
    { text: "Beli SBN Surat Berharga Ritel", text_en: "Buy Retail Government Bonds", type: "TABUNGAN" },
    { text: "Beli Sayur", text_en: "Buy Vegetables", type: "KEBUTUHAN" },
    { text: "Beli Saham Unggulan Blue Chip", text_en: "Buy Blue Chip Corporation Stocks", type: "TABUNGAN" },
    { text: "Sisihkan Gaji Bulanan Rutin", text_en: "Set Aside Routine Monthly Salary", type: "TABUNGAN" },
    { text: "Koleksi Stiker Lucu Bulan Ini", text_en: "This Month Collect Cute Stickers", type: "KEINGINAN" },
    { text: "Modus Pesugihan Online Gaib", text_en: "Online Occult Ritual Scam", type: "TRAP" },
    { text: "Beli Aksesoris Pakaian", text_en: "Buy Clothing Accessories", type: "KEINGINAN" },
    { text: "Sisihkan Dana Darurat Super Cepat dan Praktis", text_en: "Super Fast and Practical Set Aside Emergency Fund", type: "TABUNGAN" },
    { text: "Beli Tiket Konser K-Pop Bulan Depan", text_en: "Next Month Scheduled Buy K-Pop Concert Ticket", type: "KEINGINAN" },
    { text: "Bayar Premi Asuransi Jiwa", text_en: "Pay Life Insurance Premium", type: "TABUNGAN" },
    { text: "Nonton Tiket Bioskop Premier", text_en: "Watch Premier Movie Tickets", type: "KEINGINAN" },
    { text: "Sisihkan Modal Buka Usaha", text_en: "Set Aside New Business Capital", type: "TABUNGAN" },
    { text: "E-Mail Penipuan Perusahaan Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Corporate Scam Phishing Email", type: "TRAP" },
    { text: "Beli Sabun Mandi Edisi Premium Terbaru", text_en: "Latest Premium Edition Buy Bath Soap", type: "KEBUTUHAN" },
    { text: "Servis Kendaraan Bulanan", text_en: "Monthly Vehicle Service", type: "KEBUTUHAN" },
    { text: "Bayar Iuran Warga Desa", text_en: "Pay Community Dues", type: "KEBUTUHAN" },
    { text: "Simpan Uang Pangkal Sekolah", text_en: "Save for School Enrollment Funds", type: "TABUNGAN" },
    { text: "Lowongan Kerja Palsu Meminta Uang", text_en: "Fake Job Vacancy Asking Pre-Money", type: "TRAP" },
    { text: "Pinjaman KTP Bodong Ilegal", text_en: "Fake ID Illegal Loans", type: "TRAP" }
  ],
  3: [
    { text: "Tabungan Hewan Qurban", text_en: "Save for Charity Slaughter", type: "TABUNGAN" },
    { text: "Pinjaman KTP Bodong Ilegal Mingguan Biasa", text_en: "Standard Weekly Routine Fake ID Illegal Loans", type: "TRAP" },
    { text: "Bayar Sewa Kosan", text_en: "Pay Room Rent", type: "KEBUTUHAN" },
    { text: "Modus SMS Selamat Pemenang Super Cepat dan Praktis", text_en: "Super Fast and Practical Fake Winner Congratulations SMS", type: "TRAP" },
    { text: "Tabungan Koin Recehan Bulan Depan", text_en: "Next Month Scheduled Keep Coin Savings", type: "TABUNGAN" },
    { text: "Beli Susu Anak Formula Mendadak Mendesak", text_en: "Suddenly Very Urgent Buy Baby Milk Formula", type: "KEBUTUHAN" },
    { text: "Link Surat Tilang Undian Palsu", text_en: "Fake Traffic Ticket Sweepstakes", type: "TRAP" },
    { text: "Koleksi Stiker Lucu Hari Ini Secara Tunai", text_en: "Today in Cash Collect Cute Stickers", type: "KEINGINAN" },
    { text: "Setor Dana Pensiun Tua", text_en: "Deposit into Pension Fund", type: "TABUNGAN" },
    { text: "Belanja Sembako Mingguan Edisi Premium Terbaru", text_en: "Latest Premium Edition Buy Basic Weekly Groceries", type: "KEBUTUHAN" },
    { text: "Undian SMS Menang Palsu", text_en: "Fake SMS Grand Prize Sweepstakes", type: "TRAP" },
    { text: "Beli Kuota Internet Belajar", text_en: "Buy Study Data Plan", type: "KEBUTUHAN" },
    { text: "Bayar Premi Asuransi Jiwa Untuk Keluarga", text_en: "For the Extended Family Pay Life Insurance Premium", type: "TABUNGAN" },
    { text: "Nonton Tiket Bioskop Premier Super Cepat dan Praktis", text_en: "Super Fast and Practical Watch Premier Movie Tickets", type: "KEINGINAN" },
    { text: "Beli Action Figure Jutaan Bulan Depan", text_en: "Next Month Scheduled Buy Expensive Action Figure", type: "KEINGINAN" },
    { text: "Isi BBM Kendaraan Mendadak Mendesak", text_en: "Suddenly Very Urgent Refill Vehicle Fuel", type: "KEBUTUHAN" },
    { text: "Tawaran Cepat Kaya Instan Bulan Lalu Tertunda", text_en: "Delayed from Last Month Instant Get Rich Quick Offer", type: "TRAP" },
    { text: "Servis Kendaraan Bulanan", text_en: "Monthly Vehicle Service", type: "KEBUTUHAN" },
    { text: "Cicil Beli Tanah Investasi", text_en: "Installment for Land Investment", type: "TABUNGAN" },
    { text: "Grup Telegram Bot Trading Scam Edisi Premium Terbaru", text_en: "Latest Premium Edition Telegram Trading Bot Scam Group", type: "TRAP" },
    { text: "Beli Gadget HP Terbaru Bulan Ini", text_en: "This Month Buy Newest Smartphone Gadget", type: "KEINGINAN" },
    { text: "Pinjaman KTP Bodong Ilegal", text_en: "Fake ID Illegal Loans", type: "TRAP" },
    { text: "Klik Link WA Phishing Undangan", text_en: "Clicking WA Phishing Invite Link", type: "TRAP" },
    { text: "Modus SMS Selamat Pemenang Super Cepat dan Praktis", text_en: "Super Fast and Practical Fake Winner Congratulations SMS", type: "TRAP" },
    { text: "Investasi Bodong Saham Palsu Bulan Depan", text_en: "Next Month Scheduled Fake Stock Market Investment", type: "TRAP" },
    { text: "Beli Saham Unggulan Blue Chip Mendadak Mendesak", text_en: "Suddenly Very Urgent Buy Blue Chip Corporation Stocks", type: "TABUNGAN" },
    { text: "Beli Kosmetik Brand Mahal Bulan Lalu Tertunda", text_en: "Delayed from Last Month Buy Expensive Cosmetic Brands", type: "KEINGINAN" },
    { text: "Koleksi Stiker Lucu", text_en: "Collect Cute Stickers", type: "KEINGINAN" },
    { text: "Setor Dana Pensiun Tua Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Deposit into Pension Fund", type: "TABUNGAN" },
    { text: "Belanja Sembako Mingguan Edisi Premium Terbaru", text_en: "Latest Premium Edition Buy Basic Weekly Groceries", type: "KEBUTUHAN" },
    { text: "Sisihkan Dana Darurat Bulan Ini", text_en: "This Month Set Aside Emergency Fund", type: "TABUNGAN" },
    { text: "Beli Akun Game Palsu Termurah Mingguan Biasa", text_en: "Standard Weekly Routine Buy Cheapest Fake Gaming Account", type: "TRAP" },
    { text: "Jajan Minuman Teh Kekinian Untuk Keluarga", text_en: "For the Extended Family Buy Trendy Sweet Tea", type: "KEINGINAN" },
    { text: "Beli Deposito Berjangka Bank Super Cepat dan Praktis", text_en: "Super Fast and Practical Buy Bank Time Deposit", type: "TABUNGAN" },
    { text: "Sisihkan Modal Buka Usaha Bulan Depan", text_en: "Next Month Scheduled Set Aside New Business Capital", type: "TABUNGAN" },
    { text: "E-Mail Penipuan Perusahaan Mendadak Mendesak", text_en: "Suddenly Very Urgent Corporate Scam Phishing Email", type: "TRAP" },
    { text: "Beli Emas Mini Investasi Bulan Lalu Tertunda", text_en: "Delayed from Last Month Buy Investment Mini Gold", type: "TABUNGAN" },
    { text: "Servis Kendaraan Bulanan", text_en: "Monthly Vehicle Service", type: "KEBUTUHAN" },
    { text: "Voucher Hoax Diskon Belanja Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Hoax Shopping Discount Voucher", type: "TRAP" },
    { text: "Uang Ongkos Transportasi Bekerja Edisi Premium Terbaru", text_en: "Latest Premium Edition Work Commute Transport Fare", type: "KEBUTUHAN" },
    { text: "Tabungan Hewan Qurban", text_en: "Save for Charity Slaughter", type: "TABUNGAN" },
    { text: "Pinjaman KTP Bodong Ilegal Mingguan Biasa", text_en: "Standard Weekly Routine Fake ID Illegal Loans", type: "TRAP" },
    { text: "Beli Unit Reksadana Untuk Keluarga", text_en: "For the Extended Family Buy Mutual Funds Units", type: "TABUNGAN" },
    { text: "Modus SMS Selamat Pemenang", text_en: "Fake Winner Congratulations SMS", type: "TRAP" },
    { text: "Tabungan Koin Recehan Bulan Depan", text_en: "Next Month Scheduled Keep Coin Savings", type: "TABUNGAN" },
    { text: "Beli Susu Anak Formula Mendadak Mendesak", text_en: "Suddenly Very Urgent Buy Baby Milk Formula", type: "KEBUTUHAN" },
    { text: "Sisihkan Gaji Bulanan Rutin Bulan Lalu Tertunda", text_en: "Delayed from Last Month Set Aside Routine Monthly Salary", type: "TABUNGAN" },
    { text: "Bayar Listrik Hari Ini Secara Tunai", text_en: "Today in Cash Pay Electricity Bill", type: "KEBUTUHAN" },
    { text: "Modus Pesugihan Online Gaib Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Online Occult Ritual Scam", type: "TRAP" },
    { text: "Beli Aksesoris Pakaian", text_en: "Buy Clothing Accessories", type: "KEINGINAN" },
    { text: "Beli Air Minum Galon Bulan Ini", text_en: "This Month Buy Drinking Water Gallon", type: "KEBUTUHAN" },
    { text: "Beli Akun Game Palsu Termurah", text_en: "Buy Cheapest Fake Gaming Account", type: "TRAP" },
    { text: "Jajan Minuman Teh Kekinian", text_en: "Buy Trendy Sweet Tea", type: "KEINGINAN" },
    { text: "Nonton Tiket Bioskop Premier Super Cepat dan Praktis", text_en: "Super Fast and Practical Watch Premier Movie Tickets", type: "KEINGINAN" },
    { text: "Beli Pasta Gigi", text_en: "Buy Toothpaste", type: "KEBUTUHAN" }
  ],
  4: [
    { text: "Nonton Tiket Bioskop Premier Bulan Ini", text_en: "This Month Watch Premier Movie Tickets", type: "KEINGINAN" },
    { text: "Investasi Scam Kripto Abal-Abal Mingguan Biasa", text_en: "Standard Weekly Routine Fake Garbage Crypto Investment", type: "TRAP" },
    { text: "E-Mail Penipuan Perusahaan", text_en: "Corporate Scam Phishing Email", type: "TRAP" },
    { text: "Top Up Skin Game Eksklusif Super Cepat dan Praktis", text_en: "Super Fast and Practical Top Up Exclusive Game Skin", type: "KEINGINAN" },
    { text: "Liburan Staycation Hotel Mewah", text_en: "Luxury Hotel Staycation Vacation", type: "KEINGINAN" },
    { text: "Cicil Beli Tanah Investasi", text_en: "Installment for Land Investment", type: "TABUNGAN" },
    { text: "Simpan Uang Pangkal Sekolah Bulan Lalu Tertunda", text_en: "Delayed from Last Month Save for School Enrollment Funds", type: "TABUNGAN" },
    { text: "Lowongan Kerja Palsu Meminta Uang Hari Ini Secara Tunai", text_en: "Today in Cash Fake Job Vacancy Asking Pre-Money", type: "TRAP" },
    { text: "Jajan Minuman Boba", text_en: "Buy Sweet Boba Drink", type: "KEINGINAN" },
    { text: "Beli Sepatu Sneakers Modis Edisi Premium Terbaru", text_en: "Latest Premium Edition Buy Stylish Sneakers Shoes", type: "KEINGINAN" },
    { text: "Beli Vitamin Harian Keluarga", text_en: "Buy Family Daily Vitamins", type: "KEBUTUHAN" },
    { text: "Tabungan Koin Recehan", text_en: "Keep Coin Savings", type: "TABUNGAN" },
    { text: "Skema Ponzi Menguntungkan", text_en: "Highly Profitable Ponzi Scheme", type: "TRAP" },
    { text: "Bayar Kontrakan Rumah", text_en: "Pay House Lease", type: "KEBUTUHAN" },
    { text: "Bayar Listrik", text_en: "Pay Electricity Bill", type: "KEBUTUHAN" },
    { text: "Modus Pesugihan Online Gaib Mendadak Mendesak", text_en: "Suddenly Very Urgent Online Occult Ritual Scam", type: "TRAP" },
    { text: "Modal Koperasi Simpan Pinjam Bulan Lalu Tertunda", text_en: "Delayed from Last Month Deposit into Savings Cooperative", type: "TABUNGAN" },
    { text: "Beli Air Minum Galon Hari Ini Secara Tunai", text_en: "Today in Cash Buy Drinking Water Gallon", type: "KEBUTUHAN" },
    { text: "Beli Tiket Konser K-Pop Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Buy K-Pop Concert Ticket", type: "KEINGINAN" },
    { text: "Beli Lauk Pauk Sayur Mayur", text_en: "Buy Vegetables & Meats", type: "KEBUTUHAN" },
    { text: "Beli Obat-obatan Apotek", text_en: "Buy Pharmacy Medicines", type: "KEBUTUHAN" },
    { text: "Beli Action Figure Jutaan", text_en: "Buy Expensive Action Figure", type: "KEINGINAN" },
    { text: "Beli Emas Batangan Murni Untuk Keluarga", text_en: "For the Extended Family Buy Pure Gold Bar Solid", type: "TABUNGAN" },
    { text: "Beli Emas Mini Investasi", text_en: "Buy Investment Mini Gold", type: "TABUNGAN" },
    { text: "Servis Kendaraan Bulanan Bulan Depan", text_en: "Next Month Scheduled Monthly Vehicle Service", type: "KEBUTUHAN" },
    { text: "Bayar Langganan Premium Spotify Mendadak Mendesak", text_en: "Suddenly Very Urgent Pay Spotify Premium Subscription", type: "KEINGINAN" },
    { text: "Uang Ongkos Transportasi Bekerja", text_en: "Work Commute Transport Fare", type: "KEBUTUHAN" },
    { text: "Lowongan Kerja Palsu Meminta Uang Hari Ini Secara Tunai", text_en: "Today in Cash Fake Job Vacancy Asking Pre-Money", type: "TRAP" },
    { text: "Jajan Minuman Boba Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Buy Sweet Boba Drink", type: "KEINGINAN" },
    { text: "Klik Link WA Phishing Undangan Edisi Premium Terbaru", text_en: "Latest Premium Edition Clicking WA Phishing Invite Link", type: "TRAP" },
    { text: "Beli SBN Surat Berharga Ritel Bulan Ini", text_en: "This Month Buy Retail Government Bonds", type: "TABUNGAN" },
    { text: "Beli Sayur", text_en: "Buy Vegetables", type: "KEBUTUHAN" },
    { text: "Skema Ponzi Menguntungkan", text_en: "Highly Profitable Ponzi Scheme", type: "TRAP" },
    { text: "Sisihkan Gaji Bulanan Rutin", text_en: "Set Aside Routine Monthly Salary", type: "TABUNGAN" },
    { text: "Setor Rekening Bank", text_en: "Deposit into Bank Account", type: "TABUNGAN" },
    { text: "Beli Gas Dapur Habis Mendadak Mendesak", text_en: "Suddenly Very Urgent Buy Kitchen Gas Cylinder", type: "KEBUTUHAN" },
    { text: "Instal APK Kurir Ekspedisi Bodong", text_en: "Install Fake Courier Tracking APK", type: "TRAP" },
    { text: "Beli Air Minum Galon Hari Ini Secara Tunai", text_en: "Today in Cash Buy Drinking Water Gallon", type: "KEBUTUHAN" },
    { text: "Beli Akun Game Palsu Termurah Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Buy Cheapest Fake Gaming Account", type: "TRAP" },
    { text: "Jajan Minuman Teh Kekinian Edisi Premium Terbaru", text_en: "Latest Premium Edition Buy Trendy Sweet Tea", type: "KEINGINAN" },
    { text: "Aplikasi Pinjol Bunga 50% Bulan Ini", text_en: "This Month Loan Sharks App 50% Interest", type: "TRAP" },
    { text: "Beli Action Figure Jutaan", text_en: "Buy Expensive Action Figure", type: "KEINGINAN" },
    { text: "Beli Emas Batangan Murni Untuk Keluarga", text_en: "For the Extended Family Buy Pure Gold Bar Solid", type: "TABUNGAN" },
    { text: "Beli Sabun Mandi Super Cepat dan Praktis", text_en: "Super Fast and Practical Buy Bath Soap", type: "KEBUTUHAN" },
    { text: "Liburan Staycation Hotel Mewah", text_en: "Luxury Hotel Staycation Vacation", type: "KEINGINAN" },
    { text: "Cicil Beli Tanah Investasi Mendadak Mendesak", text_en: "Suddenly Very Urgent Installment for Land Investment", type: "TABUNGAN" },
    { text: "Grup Telegram Bot Trading Scam", text_en: "Telegram Trading Bot Scam Group", type: "TRAP" },
    { text: "Beli Makanan Pokok Hari Ini Secara Tunai", text_en: "Today in Cash Buy Staple Daily Foods", type: "KEBUTUHAN" },
    { text: "Isi Celengan Ayam Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Fill Piggy Bank", type: "TABUNGAN" },
    { text: "Klik Link WA Phishing Undangan", text_en: "Clicking WA Phishing Invite Link", type: "TRAP" },
    { text: "Modus SMS Selamat Pemenang", text_en: "Fake Winner Congratulations SMS", type: "TRAP" },
    { text: "Investasi Bodong Saham Palsu Mingguan Biasa", text_en: "Standard Weekly Routine Fake Stock Market Investment", type: "TRAP" },
    { text: "Beli Saham Unggulan Blue Chip Untuk Keluarga", text_en: "For the Extended Family Buy Blue Chip Corporation Stocks", type: "TABUNGAN" },
    { text: "Bayar Kontrakan Rumah", text_en: "Pay House Lease", type: "KEBUTUHAN" },
    { text: "Koleksi Stiker Lucu", text_en: "Collect Cute Stickers", type: "KEINGINAN" }
  ],
  5: [
    { text: "Bayar Kontrakan Rumah Bulan Ini", text_en: "This Month Pay House Lease", type: "KEBUTUHAN" },
    { text: "Setor Rekening Bank", text_en: "Deposit into Bank Account", type: "TABUNGAN" },
    { text: "Setor Dana Pensiun Tua Untuk Keluarga", text_en: "For the Extended Family Deposit into Pension Fund", type: "TABUNGAN" },
    { text: "Beli Aksesoris Pakaian", text_en: "Buy Clothing Accessories", type: "KEINGINAN" },
    { text: "Sisihkan Dana Darurat", text_en: "Set Aside Emergency Fund", type: "TABUNGAN" },
    { text: "Beli Tiket Konser K-Pop", text_en: "Buy K-Pop Concert Ticket", type: "KEINGINAN" },
    { text: "Transfer Uang Jebakan Pajak", text_en: "Fake Tax Trap Money Transfer", type: "TRAP" },
    { text: "Aplikasi Pinjol Bunga 50% Hari Ini Secara Tunai", text_en: "Today in Cash Loan Sharks App 50% Interest", type: "TRAP" },
    { text: "Investasi Scam Kripto Abal-Abal", text_en: "Fake Garbage Crypto Investment", type: "TRAP" },
    { text: "Isi BBM Kendaraan Edisi Premium Terbaru", text_en: "Latest Premium Edition Refill Vehicle Fuel", type: "KEBUTUHAN" },
    { text: "Beli Emas Mini Investasi Bulan Ini", text_en: "This Month Buy Investment Mini Gold", type: "TABUNGAN" },
    { text: "Telepon Tipu-Tipu Keluarga Celaka Mingguan Biasa", text_en: "Standard Weekly Routine Fake Family Accident Phone Call", type: "TRAP" },
    { text: "Bayar Langganan Premium Spotify", text_en: "Pay Spotify Premium Subscription", type: "KEINGINAN" },
    { text: "Grup Telegram Bot Trading Scam Super Cepat dan Praktis", text_en: "Super Fast and Practical Telegram Trading Bot Scam Group", type: "TRAP" },
    { text: "Lowongan Kerja Palsu Meminta Uang", text_en: "Fake Job Vacancy Asking Pre-Money", type: "TRAP" },
    { text: "Beli Beras Mendadak Mendesak", text_en: "Suddenly Very Urgent Buy Sack of Rice", type: "KEBUTUHAN" },
    { text: "Bayar Sewa Kosan Bulan Lalu Tertunda", text_en: "Delayed from Last Month Pay Room Rent", type: "KEBUTUHAN" },
    { text: "Beli Vitamin Harian Keluarga", text_en: "Buy Family Daily Vitamins", type: "KEBUTUHAN" },
    { text: "Beli Sayur Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Buy Vegetables", type: "KEBUTUHAN" },
    { text: "Beli Susu Anak Formula", text_en: "Buy Baby Milk Formula", type: "KEBUTUHAN" },
    { text: "Link Surat Tilang Undian Palsu Bulan Ini", text_en: "This Month Fake Traffic Ticket Sweepstakes", type: "TRAP" },
    { text: "Setor Rekening Bank Mingguan Biasa", text_en: "Standard Weekly Routine Deposit into Bank Account", type: "TABUNGAN" },
    { text: "Modus Pesugihan Online Gaib", text_en: "Online Occult Ritual Scam", type: "TRAP" },
    { text: "Belanja Sembako Mingguan", text_en: "Buy Basic Weekly Groceries", type: "KEBUTUHAN" },
    { text: "Sisihkan Dana Darurat", text_en: "Set Aside Emergency Fund", type: "TABUNGAN" },
    { text: "Beli Kuota Internet Belajar", text_en: "Buy Study Data Plan", type: "KEBUTUHAN" },
    { text: "Bayar Premi Asuransi Jiwa", text_en: "Pay Life Insurance Premium", type: "TABUNGAN" },
    { text: "Nonton Tiket Bioskop Premier Hari Ini Secara Tunai", text_en: "Today in Cash Watch Premier Movie Tickets", type: "KEINGINAN" },
    { text: "Beli Pasta Gigi Rutin Tiap Bulan", text_en: "Routine Monthly Dedicated Buy Toothpaste", type: "KEBUTUHAN" },
    { text: "Beli Emas Batangan Murni", text_en: "Buy Pure Gold Bar Solid", type: "TABUNGAN" },
    { text: "Beli Emas Mini Investasi", text_en: "Buy Investment Mini Gold", type: "TABUNGAN" },
    { text: "Liburan Staycation Hotel Mewah Mingguan Biasa", text_en: "Standard Weekly Routine Luxury Hotel Staycation Vacation", type: "KEINGINAN" },
    { text: "Cicil Beli Tanah Investasi", text_en: "Installment for Land Investment", type: "TABUNGAN" },
    { text: "Simpan Uang Pangkal Sekolah Super Cepat dan Praktis", text_en: "Super Fast and Practical Save for School Enrollment Funds", type: "TABUNGAN" },
    { text: "Tabungan Hewan Qurban Bulan Depan", text_en: "Next Month Scheduled Save for Charity Slaughter", type: "TABUNGAN" },
    { text: "Jajan Minuman Boba Mendadak Mendesak", text_en: "Suddenly Very Urgent Buy Sweet Boba Drink", type: "KEINGINAN" },
    { text: "Bayar Sewa Kosan Bulan Lalu Tertunda", text_en: "Delayed from Last Month Pay Room Rent", type: "KEBUTUHAN" },
    { text: "Beli Vitamin Harian Keluarga Hari Ini Secara Tunai", text_en: "Today in Cash Buy Family Daily Vitamins", type: "KEBUTUHAN" },
    { text: "Investasi Bodong Saham Palsu", text_en: "Fake Stock Market Investment", type: "TRAP" },
    { text: "Skema Ponzi Menguntungkan Edisi Premium Terbaru", text_en: "Latest Premium Edition Highly Profitable Ponzi Scheme", type: "TRAP" },
    { text: "Sisihkan Gaji Bulanan Rutin Bulan Ini", text_en: "This Month Set Aside Routine Monthly Salary", type: "TABUNGAN" },
    { text: "Bayar Listrik", text_en: "Pay Electricity Bill", type: "KEBUTUHAN" },
    { text: "Langganan Streaming VIP", text_en: "Pay VIP Streaming Subscription", type: "KEINGINAN" },
    { text: "Modal Koperasi Simpan Pinjam", text_en: "Deposit into Savings Cooperative", type: "TABUNGAN" },
    { text: "Sisihkan Dana Darurat", text_en: "Set Aside Emergency Fund", type: "TABUNGAN" },
    { text: "Beli Surat Obligasi Negara", text_en: "Buy Government Treasury Bonds", type: "TABUNGAN" },
    { text: "Jajan Minuman Teh Kekinian", text_en: "Buy Trendy Sweet Tea", type: "KEINGINAN" },
    { text: "Beli Obat-obatan Apotek Hari Ini Secara Tunai", text_en: "Today in Cash Buy Pharmacy Medicines", type: "KEBUTUHAN" },
    { text: "Investasi Scam Kripto Abal-Abal", text_en: "Fake Garbage Crypto Investment", type: "TRAP" },
    { text: "Isi BBM Kendaraan", text_en: "Refill Vehicle Fuel", type: "KEBUTUHAN" },
    { text: "Top Up Skin Game Eksklusif Bulan Ini", text_en: "This Month Top Up Exclusive Game Skin", type: "KEINGINAN" },
    { text: "Servis Kendaraan Bulanan", text_en: "Monthly Vehicle Service", type: "KEBUTUHAN" },
    { text: "Bayar Iuran Warga Desa Untuk Keluarga", text_en: "For the Extended Family Pay Community Dues", type: "KEBUTUHAN" },
    { text: "Uang Ongkos Transportasi Bekerja", text_en: "Work Commute Transport Fare", type: "KEBUTUHAN" },
    { text: "Beli Makanan Pokok Bulan Depan", text_en: "Next Month Scheduled Buy Staple Daily Foods", type: "KEBUTUHAN" }
  ]
};
